name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Start Docker Compose
        run: docker-compose up -d
      - name: Wait for Docker services to be ready
        run: sleep 10
      - name: Start SUT
        run: java -jar ./artifacts/aqa-shop.jar &
      - name: Wait for SUT to be ready
        run: |
          for i in {1..30}; do
            if curl -s -o /dev/null -w "%{http_code}" http://localhost:порт || true; then
              echo "SUT is ready!"
              break
            else
              echo "Waiting for SUT... attempt $i"
              sleep 5
            fi
          done
      - name: Build with Gradle
        run: ./gradlew test --info -Dselenide.headless=true